<?php

return [
    'friendly_urls' => [
        'key' => 'friendly_urls',
        'xtype' => 'combo-boolean',
        'value' => true,
        'area' => 'furls',
        'namespace' => 'core',
    ],
    'site_name' => [
        'key' => 'site_name',
        'xtype' => 'textfield',
        'value' => 'modx.pro',
        'area' => 'site',
        'namespace' => 'core',
    ],
    'link_tag_scheme' => [
        'key' => 'link_tag_scheme',
        'xtype' => 'textfield',
        'value' => 'abs',
        'area' => 'site',
        'namespace' => 'core',
    ],
    'emailsender' => [
        'key' => 'emailsender',
        'xtype' => 'textfield',
        'value' => 'no_reply@modx.pro',
        'area' => 'authentication',
        'namespace' => 'core',
    ],
    'session_name' => [
        'key' => 'session_name',
        'xtype' => 'textfield',
        'value' => 'MODSESSID',
        'area' => 'session',
        'namespace' => 'core',
    ],

    'pdotools_elements_path' => [
        'key' => 'pdotools_elements_path',
        'xtype' => 'textfield',
        'value' => '{core_path}components/modxpro/elements/',
        'area' => 'pdotools_main',
        'namespace' => 'pdotools',
    ],
    'ap_frontend_js' => [
        'key' => 'ap_frontend_js',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'ap_style',
        'namespace' => 'adminpanel',
    ],
    'mse2_filters_handler_class' => [
        'key' => 'mse2_filters_handler_class',
        'xtype' => 'textfield',
        'value' => 'comFilterHandler',
        'area' => 'mse2_main',
        'namespace' => 'msearch2',
    ],

    'office_frontend_css' => [
        'key' => 'office_frontend_css',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_main',
        'namespace' => 'office',
    ],
    'office_frontend_js' => [
        'key' => 'office_frontend_js',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_main',
        'namespace' => 'office',
    ],
    'office_auth_frontend_css' => [
        'key' => 'office_auth_frontend_css',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_auth',
        'namespace' => 'office',
    ],
    'office_auth_frontend_js' => [
        'key' => 'office_auth_frontend_js',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_auth',
        'namespace' => 'office',
    ],
    'office_profile_frontend_css' => [
        'key' => 'office_profile_frontend_css',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_profile',
        'namespace' => 'office',
    ],
    'office_profile_frontend_js' => [
        'key' => 'office_profile_frontend_js',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'office_profile',
        'namespace' => 'office',
    ],
    'ha.frontend_css' => [
        'key' => 'ha.frontend_css',
        'xtype' => 'textfield',
        'value' => '',
        'area' => 'ha.main',
        'namespace' => 'hybridauth',
    ],
    'ha.register_users' => [
        'key' => 'ha.register_users',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'ha.main',
        'namespace' => 'hybridauth',
    ],

    'app_mail_queue' => [
        'key' => 'app_mail_queue',
        'xtype' => 'combo-boolean',
        'value' => false,
        'area' => 'app_main',
        'namespace' => 'modxpro',
    ],
];