<?php

return [
    'web' => [
        'index' => [
            'id' => 1,
            'pagetitle' => 'Главная',
            'hidemenu' => true,
        ],
        'blogs' => [
            'pagetitle' => 'Разделы',
            'resources' => [
                'help' => [
                    'id' => 1001,
                    'pagetitle' => 'Вопросы',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'help',
                    'uri_override' => true,
                ],
                'news' => [
                    'pagetitle' => 'Новости и события',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'news',
                    'uri_override' => true,
                ],
                'hosting' => [
                    'pagetitle' => 'Хостинг',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'hosting',
                    'uri_override' => true,
                ],
                'solutions' => [
                    'pagetitle' => 'Готовые решения',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'solutions',
                    'uri_override' => true,
                ],
                'work' => [
                    'pagetitle' => 'Объявления о работе',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'work',
                    'uri_override' => true,
                ],
                'crowdfunding' => [
                    'pagetitle' => 'Краудфандинг',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'crowdfunding',
                    'uri_override' => true,
                ],
                'howto' => [
                    'pagetitle' => 'Пошаговые инструкции',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'howto',
                    'uri_override' => true,
                ],
                'store' => [
                    'pagetitle' => 'Магазин дополнений',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'store',
                    'uri_override' => true,
                ],
                'components' => [
                    'pagetitle' => 'Новые дополнения и их версии',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'components',
                    'uri_override' => true,
                ],
                'security' => [
                    'pagetitle' => 'Безопасность',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'security',
                    'uri_override' => true,
                ],
                'development' => [
                    'pagetitle' => 'Для разработчиков',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'development',
                    'uri_override' => true,
                ],
                'sites' => [
                    'pagetitle' => 'Сайты на MODX',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'sites',
                    'uri_override' => true,
                ],
            ],
        ],
        'comments' => [
            'id' => 3,
            'pagetitle' => 'Комментарии',
        ],
        'topics' => [
            'pagetitle' => 'Публикации',
        ],
        'users' => [
            'pagetitle' => 'Пользователи',
        ],
        'chat' => [
            'pagetitle' => 'Чат',
        ],
        'service' => [
            'id' => 100,
            'pagetitle' => 'Служебное',
            'template' => 0,
            'hidemenu' => true,
            'published' => false,
            'resources' => [
                'search' => [
                    'pagetitle' => 'Поиск',
                    'hidemenu' => true,
                    'uri' => 'search',
                    'uri_override' => true,
                ],
                '401' => [
                    'pagetitle' => '401 - Требуется авторизация',
                    'hidemenu' => true,
                    'uri' => '401',
                ],
                '403' => [
                    'pagetitle' => '403 - Доступ запрещён',
                    'hidemenu' => true,
                    'uri' => '403',
                ],
                '404' => [
                    'pagetitle' => '404 - Документ не найден',
                    'hidemenu' => true,
                    'uri' => '404',
                ],
                'sitemap.xml' => [
                    'pagetitle' => 'Sitemap',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'text/xml',
                    'uri' => 'sitemap.xml',
                    'uri_override' => true,
                ],
                'robots.txt' => [
                    'pagetitle' => 'Robots.txt',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'text/plain',
                    'uri' => 'robots.txt',
                    'uri_override' => true,
                ],
                'rss' => [
                    'pagetitle' => 'RSS',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'application/rss+xml',
                    'uri' => 'rss',
                    'uri_override' => true,
                ],
            ],
        ],
    ],
    'en' => [
        'index' => [
            'id' => 501,
            'pagetitle' => 'Main',
            'hidemenu' => false,
        ],
        'blogs' => [
            'pagetitle' => 'Blogs',
            'resources' => [
                'help' => [
                    'id' => 2001,
                    'pagetitle' => 'Questions',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'help',
                    'uri_override' => true,
                ],
                'news' => [
                    'pagetitle' => 'News and announcements',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'news',
                    'uri_override' => true,
                ],
                'hosting' => [
                    'pagetitle' => 'Hosting',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'hosting',
                    'uri_override' => true,
                ],
                'solutions' => [
                    'pagetitle' => 'Solutions',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'solutions',
                    'uri_override' => true,
                ],
                'work' => [
                    'pagetitle' => 'Jobs',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'work',
                    'uri_override' => true,
                ],
                'crowdfunding' => [
                    'pagetitle' => 'Crowdfunding',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'crowdfunding',
                    'uri_override' => true,
                ],
                'howto' => [
                    'pagetitle' => 'How to',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'howto',
                    'uri_override' => true,
                ],
                'store' => [
                    'pagetitle' => 'Extras store',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'store',
                    'uri_override' => true,
                ],
                'components' => [
                    'pagetitle' => 'New extras and updates',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'components',
                    'uri_override' => true,
                ],
                'security' => [
                    'pagetitle' => 'Security',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'security',
                    'uri_override' => true,
                ],
                'development' => [
                    'pagetitle' => 'For developers',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'development',
                    'uri_override' => true,
                ],
                'sites' => [
                    'pagetitle' => 'MODX sites',
                    'template' => 2,
                    'class_key' => 'TicketsSection',
                    'uri' => 'sites',
                    'uri_override' => true,
                ],
            ],
        ],
        'comments' => [
            'id' => 503,
            'pagetitle' => 'Comments',
        ],
        'topics' => [
            'pagetitle' => 'Topics',
        ],
        'users' => [
            'pagetitle' => 'Users',
        ],
        'chat' => [
            'pagetitle' => 'Chat',
        ],
        'service' => [
            'id' => 600,
            'pagetitle' => 'Service',
            'template' => 0,
            'hidemenu' => true,
            'published' => false,
            'resources' => [
                'search' => [
                    'pagetitle' => 'Search',
                    'hidemenu' => true,
                    'uri' => 'search',
                    'uri_override' => true,
                ],
                '401' => [
                    'pagetitle' => '401 - Authorization required',
                    'hidemenu' => true,
                    'uri' => '401',
                ],
                '403' => [
                    'pagetitle' => '403 - Access denied',
                    'hidemenu' => true,
                    'uri' => '403',
                ],
                '404' => [
                    'pagetitle' => '404 - Page not found',
                    'hidemenu' => true,
                    'uri' => '404',
                ],
                'sitemap.xml' => [
                    'pagetitle' => 'Sitemap',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'text/xml',
                    'uri' => 'sitemap.xml',
                    'uri_override' => true,
                ],
                'robots.txt' => [
                    'pagetitle' => 'Robots.txt',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'text/plain',
                    'uri' => 'robots.txt',
                    'uri_override' => true,
                ],
                'rss' => [
                    'pagetitle' => 'RSS',
                    'template' => 0,
                    'hidemenu' => true,
                    'content_type' => 'application/rss+xml',
                    'uri' => 'rss',
                    'uri_override' => true,
                ],
            ],
        ],
    ],
];